// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace DouBanFM.Entities
{

    public class Channel
    {

        [JsonProperty("name_en")]
        public string NameEn { get; set; }

        [JsonProperty("seq_id")]
        public int SeqId { get; set; }

        [JsonProperty("abbr_en")]
        public string AbbrEn { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("channel_id")]
        public object ChannelId { get; set; }
    }

}
