// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.ObjectModel;

namespace DouBanFM.Entities
{

    public class ChannelsResult
    {

        [JsonProperty("channels")]
        public ObservableCollection<Channel> Channels { get; set; }
    }

}
